### PR TITLE
Gradle upgrade #3

### PR DESCRIPTION
**Pull request by bsamartins**
Changes for #3:
- Drop `querydsl` source set in favour of adding a new source directory to the `main` source set
- Remove no longer necessary directory creation task `InitQuerydslSourcesDir`

### CODE REVIEW

**Comment by holgerstolzenberg** [comment]
@bsamartins as this is still a DRAFT, should I start the review or are there still things to come? Thanks for your work with the other pull requests so far.

**Comment by bsamartins** [comment]
@holgerstolzenberg, here are the changes done: 

- Dropped the querydsl sourceSet and `QuerdslPluginExtension. querydslSourcesDir`. 
Instead of generated sources being added to path under the querydsl source set, they will be added to the java compile task `annotationProcessorGeneratedSourcesDirectory` (and consequentially included in the compilation sources).

- Dropped the querydsl configuration. 
Rather than the annotation processor dependencies being declared using the `querydsl` configuration, the standard `annotationProcessor` should be used instead.
``` kotlin
// before
querydsl("org.projectlombok:lombok:1.18.8")

// after
annotationProcessor("org.projectlombok:lombok:1.18.8")
```

- A similar approach for registering the compile tasks in the java plugin was followed here.
For each source set there will be a QuerydslCompile task registered (`main` -> `compileQuerydsl`, `test` -> `testCompileQuerydsl`).
If a new source set is configured (e. g. `intTest`), the plugin is registers a new new compile task, `intTestCompileQuerydsl` and additionally specific annotation processor classpath can be used for that source set, using the `intTestAnnotationProcessor` configuration.

 - Since the annotation processor directory is created by the JavaCompile task, the InitQuerydslSourcesDir was removed. Same for the clean task, since the generated sources, by default, go into the build dir, it can be replaced with the clean task.

I'd like to have your feedback on this.

There's are still some things to tidy up comments and further tests to be done.
I suppose the idea of the draft PR was to get discussion up on the refactoring.

I setup a repo with a couple of sample projects that I have been using to test the changes (we could consider integrating these later into the plugin repo or some other repo).

**Comment by holgerstolzenberg** [comment]
Sounds all fine to me. You can do your cleanup stuff and then I´ll do the final release so that we can get the release of the plugin rolling.

I´d like to put the samples into a distinct repo like `ewerk/querydsl-plugin-samples`. I´ll create the repo and give you access.

**Comment by holgerstolzenberg** [comment]
I´ve created the repo, you should have gotten the invite link already.

https://github.com/ewerk/querydsl-plugin-samples

**Comment by bsamartins** [comment]
Apologies for only updating the PR/branch now, but got sidetracked with other things.

**Review by holgerstolzenberg — APPROVED** [review]

**Pull request merged**
